server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:drinkdb
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  storageCapacityAlcoholic = '500'
#  storageCapacityNonAlcoholic = '400'
